### ISSUE TITLE
public void parseExpressionWithCommandArray() throws IOException  fails

### ISSUE THREAD

**Issue by anywhereinfo** [yaml-path/YamlPath#120]
It fails as shown below. Why do you have a check that if size > 1, throw IllegalStateException?  At the same time, in test , rightfully so, you expect 2 values
java.lang.IllegalStateException: Several results found: [[], [[command1, command2]]]
	at io.github.yamlpath.utils.SetUtils.uniqueResult(SetUtils.java:12)
	at io.github.yamlpath.YamlExpressionParser.readSingleAndReplace(YamlExpressionParser.java:148)
	at io.github.yamlpath.YamlExpressionParserTest.parseExpressionWithCommandArray(YamlExpressionParserTest.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at

**Comment by Sgitario** [comment]
This test is not failing. Can you provide more details about what triggers your failure?
By the way, this test is using `readSingleAndReplace` which means that it's expected to find only one result (which is the list of the commands).

**Comment by Sgitario** [comment]
@anywhereinfo , https://github.com/yaml-path/YamlPath/pull/123 should fix the issue you mentioned.
